# Generated by Django 3.2 on 2023-09-29 14:17

from django.db import migrations, models
import django.db.models.deletion
from ..constants import *

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membername', models.CharField(max_length=20)),
                ('gender', models.IntegerField(max_length=20,choices=[(0, '男性'), (1, '女性'), (2, 'その他')])),
                ('tel', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=30)),
                ('numbers', models.IntegerField(choices=PLACE_NUMBER_CHOICES)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kinds', models.CharField(max_length=20, choices=CAR_CHOICES )),
                ('datetime', models.DateTimeField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pickupapp.membermodel')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pickupapp.placemodel')),
            ],
        ),
    ]
